document:
  name: Attuazione della Politica dei Dati dell'INGV
  description: |
    Attuazione della Politica dei Dati dell'Istituto Nazionale di Geofisica e Vulcanologia.
  tags:
    - INGV
    - politica dei dati
    - database
    - dataset
    - ricerca scientifica
    - metadati
    - FAIR
