version: 2
jobs:
  job_1:
    docker:
      - image: python:3.7
    steps:
      - checkout
      - run:
          name: Install OS packages
          command: |
            apt-get update
            apt-get install -y \
              latex-xcolor \
              latexmk
      - run:
          name: Install dependencies
          command: pip install -r requirements.txt
      - run:
          name: Use Sphinx to make the html docs
          command: |
            pwd
            ls -l
            make html
            make latexpdf
            cp _build/latex/*.pdf _build/html/
            make epub
            cp _build/epub/*.epub _build/html/
            # Tell GitHub not to use jekyll to compile the docs
            touch _build/html/.nojekyll
            
workflows:
  version: 2
  build_valentino:
    jobs:
      - job_1
