version: 2
jobs:
  job_1:
    docker:
      - image: python:3.7
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: pip install -r requirements.txt
      - run:
          name: Use Sphinx to make the html docs
          command: |
            sphinx-build -M html "." "_build"
            
workflows:
  version: 2
  build_valentino:
    jobs:
      - job_1
